---
version: '3.9'

services:
  wp:
    image: wordpress:latest
    container_name: wp-site
    depends_on:
      - db
    networks:
      - lan
    volumes:
      - html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
    healthcheck:
      test: [CMD, curl, -f, http://localhost]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 0s

  db:
    image: mariadb:latest
    container_name: wp-db
    networks:
      - lan
    volumes:
      - db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: wordpress
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    healthcheck:
      test: [CMD, mysqladmin, ping, -h, localhost]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 0s

volumes:
  db:
  html:

networks:
  lan:


# vim: ft=yaml tw=80 et ts=2 sw=2 sts=2
