version: '3.7'

services:
  site:
    image: wordpress
    depends_on:
      - db
    #restart: always
    networks:
      - lan
      - traefik_wan
    volumes:
      - html:/var/www/html
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:www.domain.tld'
      - 'traefik.port=80'
      - 'traefik.docker.network=traefik_wan'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 0s

  db:
    image: mysql:5.6
    #restart: always
    networks:
      - lan
      - db-lan
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 0s

volumes:
  db:
  html:

networks:
  lan: 
  db-lan: 
    external: True
  traefik_wan:
    external: True


# vim: ft=yaml tw=80 et ts=2 sw=2 sts=2
